"""Probe every candidate ATS token and write config/companies.yaml with the ones that respond.

  python scripts/verify_companies.py
"""
from __future__ import annotations

import asyncio
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from jobscraper.http import Client  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent


async def probe(client: Client, ats: str, token: str) -> tuple[str, int] | None:
    """Returns (display name, open job count) or None."""
    if ats == "greenhouse":
        d = await client.get_json(f"https://boards-api.greenhouse.io/v1/boards/{token}")
        if not d:
            return None
        jobs = await client.get_json(f"https://boards-api.greenhouse.io/v1/boards/{token}/jobs")
        return d.get("name") or token, len((jobs or {}).get("jobs", []))
    if ats == "lever":
        d = await client.get_json(f"https://api.lever.co/v0/postings/{token}?mode=json&limit=500")
        return (token.replace("-", " ").title(), len(d)) if isinstance(d, list) and d else None
    if ats == "ashby":
        d = await client.get_json(f"https://api.ashbyhq.com/posting-api/job-board/{token}")
        return (token.title(), len(d.get("jobs", []))) if d and d.get("jobs") else None
    if ats == "smartrecruiters":
        d = await client.get_json(f"https://api.smartrecruiters.com/v1/companies/{token}/postings?limit=1")
        n = (d or {}).get("totalFound", 0)
        return (token, n) if n else None
    if ats == "workday":
        tenant, wd, site = token.split("|")
        d = await client.post_json(
            f"https://{tenant}.{wd}.myworkdayjobs.com/wday/cxs/{tenant}/{site}/jobs",
            json={"appliedFacets": {}, "limit": 1, "offset": 0, "searchText": ""},
        )
        n = (d or {}).get("total", 0)
        return (tenant.title(), n) if n else None
    return None


async def main():
    cands = yaml.safe_load((ROOT / "scripts" / "candidates.yaml").read_text(encoding="utf-8"))
    names = {k.lower(): v for k, v in (cands.pop("names", None) or {}).items()}
    tasks, meta = [], []
    seen = set()
    for tag, by_ats in cands.items():
        for ats, tokens in by_ats.items():
            for t in tokens:
                t = str(t).strip()
                if " " in t or (ats, t.lower()) in seen:
                    continue
                seen.add((ats, t.lower()))
                meta.append((tag, ats, t))
    async with Client(per_host=10, timeout=20, retries=1) as client:
        tasks = [probe(client, ats, t) for _, ats, t in meta]
        results = await asyncio.gather(*tasks, return_exceptions=True)

    out, dedup = [], set()
    for (tag, ats, t), r in zip(meta, results):
        if isinstance(r, tuple):
            name, n = r
            name = names.get(t.split("|")[0].lower(), name)
            key = name.lower().replace(" ", "")
            if (key, ats) in dedup:
                continue
            dedup.add((key, ats))
            out.append({"name": name, "ats": ats, "token": t, "tag": tag, "open_jobs": n})
    out.sort(key=lambda c: (c["tag"], c["ats"], c["name"].lower()))
    (ROOT / "config" / "companies.yaml").write_text(
        "# Generated by scripts/verify_companies.py — edit scripts/candidates.yaml instead.\n"
        + yaml.safe_dump({"companies": out}, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    from collections import Counter
    print(f"{len(out)}/{len(meta)} verified:", dict(Counter(c["ats"] for c in out)))


if __name__ == "__main__":
    asyncio.run(main())
